### PR TITLE
desktop vs mobile run all tests

### PR DESCRIPTION
**Pull request by bahmutov**
just an idea how to run all tests using mobile viewport and desktop viewport
- another alternative is to run just a few tests in several resolutions (see viewport-spec.js)
- another alternative would be to run on CI npm command against full spec but with config viewport changed to mobile

### CODE REVIEW

**Comment by bahmutov** [comment]
just thinking how to cover viewport resolutions better for an app

**Comment by amirrustam** [comment]
I think this is one of those personal preference things, but I do like seeing the devices under test within my test code.

With that said, I think we should go beyond this and set the proper user-agent for the specified device. In the past I've served different apps/experiences based off UA. So maybe we could have a custom command or plugin:
```js
cy.setDevice('iphone-6') // set viewport and UA
```

We can set the UA via `Cypress.config` or `cy.visit('http://internet', { headers: { user-agent: 'iphone UA' } })`.

**Comment by amirrustam** [comment]
@bahmutov and I discussed some of this on Slack, but now I have a plugin idea, I'm going to experiment with over the weekend.

**Comment by bahmutov** [comment]
Ohhh when Amir has an idea to experiment that’s exciting times ahead

**Review by amirrustam — APPROVED** [review]

**Pull request merged**
